#!/usr/bin/env bash
# Sync repo nginx/ → /etc/nginx/, then reload.
#
# Copies (not symlinks) so /etc/nginx is self-contained and doesn't break if
# the repo is moved. Project conf.d entries are still symlinks (managed by
# add-project.sh) — those are NOT touched by sync-nginx.
#
# What gets synced:
#   nginx/nginx.conf                  → /etc/nginx/nginx.conf
#   nginx/snippets/*.conf             → /etc/nginx/snippets/
#   nginx/conf.d/_default.conf        → /etc/nginx/conf.d/_default.conf
#   nginx/conf.d/*.template           → /etc/nginx/conf.d/  (templates only;
#                                       they're never loaded by nginx because
#                                       it includes only *.conf)
#
# What does NOT get synced (project state lives only on the host):
#   /etc/nginx/conf.d/<project>.conf  symlinks created by add-project.sh
#   /etc/nginx/conf.d/portainer.conf  generated by up-portainer.sh

set -euo pipefail

# shellcheck source=lib/common.sh
source "$(dirname "$(readlink -f "$0")")/lib/common.sh"

require_root_or_sudo

src="$REPO_ROOT/nginx"
[[ -d "$src" ]] || die "missing $src"

log "syncing nginx.conf"
sudo install -m 0644 "$src/nginx.conf" /etc/nginx/nginx.conf

log "syncing snippets/"
sudo mkdir -p /etc/nginx/snippets
sudo find "$src/snippets" -maxdepth 1 -type f -name '*.conf' -print0 \
  | xargs -0 -I{} sudo install -m 0644 {} /etc/nginx/snippets/

log "syncing _default.conf"
sudo install -m 0644 "$src/conf.d/_default.conf" /etc/nginx/conf.d/_default.conf

log "ensuring webroot exists"
sudo mkdir -p /var/www/certbot
sudo chown -R www-data:www-data /var/www/certbot 2>/dev/null \
  || sudo chown -R nginx:nginx /var/www/certbot 2>/dev/null \
  || true

log "validating nginx config"
sudo nginx -t

log "reloading nginx"
sudo systemctl reload nginx
ok "nginx synced and reloaded"
